"""Ingest: read original sources, have local Gemma draft linked wiki notes, rebuild index.md and the retrieval index.

Re-ingestion never creates duplicates: note filenames come from the source catalog
(config/sources.json), so the same section always maps to the same file. An unchanged
source (same SHA-256 hash) is skipped unless --force is given.
"""
import hashlib
import json
import re
import time
from datetime import datetime

from . import config
from .chunking import split_sections, strip_frontmatter
from .evidence import run_header, save_run
from .model import LocalGemma
from .prompts import link_messages, note_messages
from .retrieval import build_index


# ---------- catalog and manifest ----------

def load_json(path, default):
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else default


def fallback_title(heading):
    """Readable name for a section missing from the catalog: drop numbering and prefixes."""
    title = re.sub(r"^\d+\.\s*", "", heading)
    title = title.split(":")[-1] if ":" in title else title
    title = re.sub(r"\(.*?\)", "", title)
    return re.sub(r"[\\/#|^\[\]\"]", "", title).strip()[:60] or "Untitled"


def source_meta(path, catalog):
    meta = catalog.get(path.name, {})
    return {
        "source_id": meta.get("source_id", re.sub(r"[^a-z0-9]+", "-", path.stem.lower()).strip("-")),
        "folder": meta.get("folder", "General"),
        "notes": meta.get("notes", {}),
    }


# ---------- note generation ----------

def parse_note(text):
    text = text.replace("**", "")
    summary = re.search(r"SUMMARY:\s*(.*?)(?:\n\s*KEY POINTS:|\Z)", text, re.S | re.I)
    points = re.search(r"KEY POINTS:\s*(.*)", text, re.S | re.I)
    summary = " ".join(summary.group(1).split()) if summary else " ".join(text.split()[:80])
    bullets = []
    if points:
        bullets = [line.strip()[1:].strip() for line in points.group(1).splitlines()
                   if line.strip().startswith(("-", "*", "•"))]
    return summary, bullets


def parse_links(text, title, candidates):
    """Keep only links whose title exactly matches an existing note: Gemma cannot invent pages."""
    lookup = {c.lower(): c for c in candidates if c != title}
    links = []
    for line in text.replace("**", "").splitlines():
        if "|" not in line:
            continue
        name, reason = line.split("|", 1)
        name = name.strip().strip("-*[] ").strip()
        match = lookup.get(name.lower())
        if match and match not in [l[0] for l in links]:
            links.append((match, reason.strip()))
    return links[:3]


def render_note(note):
    front = {
        "title": note["title"],
        "source_id": note["source_id"],
        "source_file": note["source_file"],
        "source_sections": note["sections"],
        "source_sha256": note["sha256"],
        "generated_by": config.MODEL_ID,
        "generated_at": note["generated_at"],
    }
    lines = ["---"] + [f"{k}: {json.dumps(v)}" for k, v in front.items()] + ["---", "",
             f"# {note['title']}", "", "## Summary", "", note["summary"], "", "## Key points", ""]
    lines += [f"- {b}" for b in note["points"]] or ["- (none extracted)"]
    lines += ["", "## Related notes", ""]
    lines += [f"- [[{t}]]: {why}" for t, why in note["links"]] or ["- (none yet)"]
    source_name = note["source_file"].split("/")[-1].removesuffix(".md")
    lines += ["", "## Sources", ""]
    lines += [f'- [[{source_name}]], section "{s}"' for s in note["sections"]]
    return "\n".join(lines) + "\n"


def read_summary(path):
    body = strip_frontmatter(path.read_text(encoding="utf-8"))
    match = re.search(r"## Summary\s+(.*?)\n\s*\n", body, re.S)
    return " ".join(match.group(1).split()) if match else ""


def first_sentence(text):
    return re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0] if text else ""


# ---------- index.md ----------

def write_index_md(catalog):
    folders = {}
    for path in sorted(config.WIKI_DIR.rglob("*.md")):
        folder = path.parent.relative_to(config.WIKI_DIR).as_posix()
        folders.setdefault(folder, []).append((path.stem, first_sentence(read_summary(path))))
    descriptions = {m.get("folder"): m.get("description", "") for m in catalog.values()}
    lines = ["# Personal Wiki Index", "",
             "Landing page for my personal memory. Notes are grouped by topic; every note links back "
             "to the unchanged original it came from. Generated by `wiki ingest`, reviewed by me.", ""]
    for folder in sorted(folders):
        lines += [f"## {folder}", ""]
        if descriptions.get(folder):
            lines += [descriptions[folder], ""]
        lines += [f"- [[{title}]]: {desc}" for title, desc in folders[folder]] + [""]
    lines += ["## Original sources", "", "Unchanged originals in `raw/`.", ""]
    lines += [f"- [[{p.stem}]]" for p in sorted(config.RAW_DIR.glob("*.md"))]
    config.INDEX_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------- main entry ----------

def run_ingest(target, force=False):
    target = target.resolve()
    if not target.exists():
        raise FileNotFoundError(f"Not found: {target}")
    files = [target] if target.is_file() else sorted(target.glob("*.md"))
    if not files:
        raise FileNotFoundError(f"No .md files in {target}")
    for f in files:
        if config.RAW_DIR.resolve() not in f.parents:
            raise ValueError(f"{f.name} is not in vault/raw. Copy originals there first; ingest never edits them.")

    catalog = load_json(config.CATALOG_FILE, {})
    manifest = load_json(config.MANIFEST_FILE, {})
    gemma, new_notes, report = None, [], []
    start = time.perf_counter()

    for f in files:
        rel = f.relative_to(config.VAULT).as_posix()
        text = f.read_text(encoding="utf-8")
        sha = hashlib.sha256(text.encode()).hexdigest()
        previous = manifest.get(rel, {})
        if previous.get("sha256") == sha and not force:
            report.append(f"{rel}: unchanged, skipped (use --force to regenerate)")
            continue
        if gemma is None:
            print(f"Loading {config.MODEL_ID} (local)...")
            gemma = LocalGemma()
        meta = source_meta(f, catalog)

        # Group sections by note title: the catalog can merge several sections into one note
        grouped = {}
        for section in split_sections(text):
            title = meta["notes"].get(section.heading) or fallback_title(section.heading)
            grouped.setdefault(title, []).append(section)

        written = []
        for title, sections in grouped.items():
            source_text = "\n\n".join(f"## {s.heading}\n{s.text}" for s in sections)
            print(f"  drafting note: {title}")
            summary, points = parse_note(gemma.generate(
                note_messages(title, source_text), config.INGEST_MAX_TOKENS, config.INGEST_TEMPERATURE))
            path = config.WIKI_DIR / meta["folder"] / f"{title}.md"
            note = {"title": title, "path": path, "source_id": meta["source_id"], "source_file": rel,
                    "sections": [s.heading for s in sections], "sha256": sha,
                    "generated_at": datetime.now().isoformat(timespec="seconds"),
                    "summary": summary, "points": points, "links": []}
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(render_note(note), encoding="utf-8")
            written.append(note)

        # Remove notes this source produced before but no longer does (for example after a rename)
        keep = {n["path"].relative_to(config.VAULT).as_posix() for n in written}
        for old in previous.get("notes", []):
            if old not in keep and (config.VAULT / old).exists():
                (config.VAULT / old).unlink()
                report.append(f"{rel}: removed outdated note {old}")
        existed = set(previous.get("notes", []))
        created = sum(1 for k in keep if k not in existed)
        manifest[rel] = {"sha256": sha, "source_id": meta["source_id"], "notes": sorted(keep),
                         "ingested_at": datetime.now().isoformat(timespec="seconds")}
        report.append(f"{rel}: {len(written)} notes written ({created} new, {len(written) - created} updated)")
        new_notes += written

    # Linking pass: Gemma picks related notes from the full list of real titles
    if new_notes:
        candidates = sorted(p.stem for p in config.WIKI_DIR.rglob("*.md"))
        for note in new_notes:
            print(f"  linking: {note['title']}")
            reply = gemma.generate(link_messages(note["title"], note["summary"],
                                                 [c for c in candidates if c != note["title"]]),
                                   200, config.INGEST_TEMPERATURE)
            note["links"] = parse_links(reply, note["title"], candidates)
            note["path"].write_text(render_note(note), encoding="utf-8")

    write_index_md(catalog)
    passages = build_index()
    config.DATA_DIR.mkdir(exist_ok=True)
    config.MANIFEST_FILE.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    total = round(time.perf_counter() - start, 1)
    stats = {"total_seconds": total, "notes_generated": len(new_notes), "passages_indexed": len(passages)}
    if gemma:
        stats.update({"model_load_seconds": gemma.load_seconds,
                      "peak_model_memory_gb": gemma.last.get("peak_model_memory_gb"),
                      "process_peak_rss_gb": gemma.last.get("process_peak_rss_gb")})
    print("\n" + "\n".join(report))
    print(f"Index rebuilt: {len(passages)} passages. Total time {total} s.")
    path = save_run("ingest", {**run_header("ingest"), "query": str(target.relative_to(config.ROOT)),
                               "stats": stats, "details": {"report": report}})
    print(f"Saved: {path.relative_to(config.ROOT)}")
